docs: Add AWS region enablement documentation
coreos/fedora-coreos-pipeline pull request #1024
Opened 2024-08-28 22:13 UTC by aaradhak

Added a document detailing the steps for enabling AWS regions. Updated the check-aws-regions.Jenkinsfile to include a link to the new documentation.

2024-08-29 14:25 UTC, jbtrystram requested changes
for completess let's ask in the same ticket to adjust the qota, as per https://pagure.io/fedora-infrastructure/issue/11707#comment-891844

2024-08-29 14:25 UTC, jbtrystram commented on docs/aws-region-enable.md
> +        "aws ec2 disable-image-block-public-access --region `<missing-region>`"
let's also ask for the qota increase so all the regions have the same settings : 

```suggestion
        "aws ec2 disable-image-block-public-access --region `<missing-region>`"
Let's also adjust the qota to match the other regions : 
        "aws service-quotas request-service-quota-increase --region=`<missing-region` --service-code=ec2 --quota-code=L-0E3CBAB9 --desired-value 1000.00"        
```

2024-08-29 14:43 UTC, jbtrystram approved these changes
lgtm

2024-08-29 15:54 UTC, dustymabe commented on jobs/check-aws-regions.Jenkinsfile
> +/* Note: AWS region enablement, refer to the documentation here: [AWS Region Enablement](docs/aws-region-enable.md) */
I feel like maybe we should include the link (i.e. clickable) in the slack message that gets sent to the channel.

i.e. the notification sends us somewhere with the steps to take. we don't have to remember where the docs are.

2024-08-29 22:06 UTC, dustymabe approved these changes
LGTM - maybe do a test run to make sure the formatting looks good in the slack message.

Thanks for doing this.

2024-09-04 17:51 UTC, aaradhak commented
Tested & working as expected, posting the [slack message](https://redhat-internal.slack.com/archives/C045GH4M2HY/p1725472070501289) for reference

2024-09-04 17:52 UTC, merged