Add Apple Hypervisor (applehv) to default artifacts
coreos/fedora-coreos-pipeline pull request #905
Opened 2023-08-22 17:52 UTC by baude

See coreos/fedora-coreos-tracker#1533 and coreos/fedora-coreos-tracker#1548

2023-08-22 18:27 UTC, dustymabe commented
Converting to draft. IIUC this requires some work to land in Ignition and possibly a few other places (afterburn, fedora-coreos-config) before we want to start generating artifacts.

2023-08-22 18:28 UTC, dustymabe commented
The actual changes here look good and we should be able to merge them when all the other deps are in place.

2023-11-16 21:06 UTC, dustymabe requested changes

2023-11-16 21:06 UTC, dustymabe commented on config.yaml
> +    -applehv
```suggestion
    - applehv
```

2023-11-21 17:53 UTC, dustymabe approved these changes
LGTM

2023-11-28 13:57 UTC, travier commented
Is this still a draft?

2023-11-28 14:33 UTC, dustymabe commented
Ignition finally landed in all streams yesterday. I'll get the other PRs merged and then merge this too.

2023-11-28 19:37 UTC, merged